version: '3'
services:
  esor-kali:
    image: kali-vnc-esorone:latest
    tty: true
    container_name: kali-vnc-esorone
    hostname: esor-kali
    ports:
      - "2222:22"
      - "5900:5900"
      - "5901:5901"
      - "9020:9020"
    command: /usr/sbin/sshd -D
 
